#!/usr/bin/env ruby

@list_arr = [["-", "perform animal movement exercises"], ["+", "write good code"]]

def print_array(arbitrary)
  puts "\n***"
  @list_arr.map.each_with_index{|x,i| puts "#{i+1}. #{x.join(" ")}"}
  print "***\n\n"
end

def quotes(response)
  if response.match(/\s/)
    unless response[0] && response[-1] == '"'
    puts 'ERROR, please wrap words in quotes'
    end
  end
  response.gsub!(/\A"|"\Z/, '')
end

def add(response)
 #if response.match(/\s/)
   #unless response[0] && response[-1] == '"'
   #puts 'ERROR, please wrap words in quotes'
   #exit
   #end
     #response.gsub!(/\A"|"\Z/, '')
 #end
  @list_arr << ["-", response]
end

def remove(response)
  @list_arr.delete_at(response.to_i-1)
end

def done(response)
  todo_item_number = @list_arr[response.to_i-1]
  todo_item_number[0] = "+"
end

def undone(response)
  todo_item_number = @list_arr[response.to_i-1]
  todo_item_number[0] = "-"
end

def up(response)
  @list_arr[response.to_i-2], @list_arr[response.to_i-1] = @list_arr[response.to_i-1], @list_arr[response.to_i-2]
end

def down(response)
    @list_arr[response.to_i-1], @list_arr[response.to_i] = @list_arr[response.to_i], @list_arr[response.to_i-1]
end

def prompt()
  print 'todo> '
end

prompt

while input = gets.strip.downcase do
  command = input.split(' ').delete_at(0)
  response = input.split(' ')[1..-1].join(' ')

  if response.match(/\s/) && response[0] && response[-1] == '"'
  else !response.strip.include? " "
      if command == 'add'
        add(response)
      elsif command == 'remove'
        remove(response)
      elsif command == 'done'
        done(response)
      elsif command == 'undone'
        undone(response)
      elsif command == 'up'
        up(response)
      elsif command == 'down'
        down(response)
      elsif command == 'edit'
        edit(arr) 
      elsif command == 'exit'
        exit
      elsif command == 'list'
      else puts 'ERROR Unknown command, try again.'
    end
  end
  
  print_array(@list_arr)
  prompt
end
