#!/usr/bin/env ruby

@todo_list = [["-", "perform animal movement exercises"], ["+", "write good code"]]

def print_todo_list(arbitrary)
  puts "\n***"
  @todo_list.map.each_with_index{|task,i| puts "#{i+1}. #{task.join(" ")}"}
  print "***\n\n"
end

def add(response)
  @todo_list << ["-", response]
end

def remove(response)
  @todo_list.delete_at(response.to_i-1)
end

def done(response)
  todo_item_number = @todo_list[response.to_i-1]
  todo_item_number[0] = "+"
end

def undone(response)
  todo_item_number = @todo_list[response.to_i-1]
  todo_item_number[0] = "-"
end

def up(response)
  @todo_list[response.to_i-2], @todo_list[response.to_i-1] = @todo_list[response.to_i-1], @todo_list[response.to_i-2]
end

def down(response)
    @todo_list[response.to_i-1], @todo_list[response.to_i] = @todo_list[response.to_i], @todo_list[response.to_i-1]
end

def prompt()
  print 'todo> '
end

prompt

while input = gets.strip.downcase do
  command = input.split(' ').delete_at(0)
  response = input.split(' ')[1..-1].join(' ')

      if command == 'add'
        add(response)
      elsif command == 'remove'
        remove(response)
      elsif command == 'done'
        done(response)
      elsif command == 'undone'
        undone(response)
      elsif command == 'up'
        up(response)
      elsif command == 'down'
        down(response)
      elsif command == 'edit'
        edit(arr) 
      elsif command == 'exit'
        File.open("todo.txt", "w+") do |f|
          @todo_list.each { |element| f.puts(element.join(" ")) }
        end
          exit
      elsif command == 'list'
      else puts 'ERROR Unknown command, try again.'
      end
  
  print_todo_list(@todo_list)
  prompt
end
